CREATE TABLE tx
(  tx_hash BIGINT  NOT NULL ,
  gas_limit TEXT NOT NULL ,
  gas_price TEXT NOT NULL ,
  gas_used TEXT NOT NULL ,
  mini_block_hash BIGINT  NOT NULL ,
  nonce TEXT NOT NULL ,
  receiver BIGINT  NOT NULL ,
  receiver_shard TEXT NOT NULL ,
  round TEXT NOT NULL ,
  sender BIGINT  NOT NULL ,
  sender_shard TEXT NOT NULL ,
  signature BIGINT  NOT NULL ,
  status BIGINT  NOT NULL ,
  value BIGINT  NOT NULL ,
  fee BIGINT  NOT NULL ,
  timestamp TEXT NOT NULL ,
  data BIGINT  NOT NULL ,
  token_identifier JSONB  NOT NULL ,
  action JSONB  NOT NULL ,
  scam_info JSONB  NOT NULL
);

CREATE TABLE smart_contract_result
(  tx_hash BIGINT  NOT NULL ,
  hash BIGINT  NOT NULL ,
  timestamp TEXT NOT NULL ,
  nonce TEXT NOT NULL ,
  gas_limit TEXT NOT NULL ,
  gas_price TEXT NOT NULL ,
  value BIGINT  NOT NULL ,
  sender BIGINT  NOT NULL ,
  receiver BIGINT  NOT NULL ,
  relayed_value BIGINT  NOT NULL ,
  data BIGINT  NOT NULL ,
  prev_tx_hash BIGINT  NOT NULL ,
  original_tx_hash BIGINT  NOT NULL ,
  call_type BIGINT  NOT NULL ,
  logs BIGINT  NOT NULL
);